spring:
   profiles:
      active: dev

---
server:
   port:8021
spring:
   profiles: dev
   application:
      name: springcloud-config

---
server:
   port:8022
spring:
   profiles: test
   application:
      name: springcloud-config


